In [1]:
import numpy

In [2]:
a = numpy.array([8, 10, -1, 0, 0])

In [3]:
a = a[numpy.newaxis, :]
a

array([[ 8, 10, -1,  0,  0]])

In [5]:
a = numpy.array([8, 10, -1, 0, 0])
a = a[: , numpy.newaxis]
a

array([[ 8],
       [10],
       [-1],
       [ 0],
       [ 0]])

In [6]:
a = numpy.array([8, 10, -1, 0, 0])
a = a.reshape((1,5))
a

array([[ 8, 10, -1,  0,  0]])

In [7]:
a = numpy.array([8, 10, -1, 0, 0])
a = a.reshape((5,1))
a

array([[ 8],
       [10],
       [-1],
       [ 0],
       [ 0]])

In [10]:
numpy.array([False, True])

array([False,  True])